# Generated by Django 3.1.5 on 2022-06-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0004_auto_20220625_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSize',
            new_name='ProductDetail',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_id',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='productDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swoosh_app.productdetail'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
