# Generated by Django 3.1.5 on 2022-06-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0005_auto_20220625_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='productDetail',
            new_name='productDetail_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='team',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='size',
            new_name='size_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_id',
        ),
    ]
