# Generated by Django 3.1.5 on 2022-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0006_auto_20220625_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='size',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
