# Generated by Django 3.1.5 on 2022-06-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0007_auto_20220625_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='size_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swoosh_app.size'),
        ),
    ]
