# Generated by Django 3.1.5 on 2022-06-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0008_auto_20220625_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='productDetail_id',
        ),
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swoosh_app.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swoosh_app.size'),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
