# Generated by Django 4.0.5 on 2022-06-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0015_remove_orderdetails_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_id',
        ),
    ]
