# Generated by Django 4.0.5 on 2022-06-26 17:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0018_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='099999999', max_length=128, region=None, unique=True),
        ),
    ]
