# Generated by Django 4.0.5 on 2022-06-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0027_alter_brand_id_alter_category_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='total_price',
        ),
    ]
