# Generated by Django 4.0.5 on 2022-06-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0029_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
