# Generated by Django 4.0.5 on 2022-06-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0031_alter_orderdetails_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='quantity',
        ),
    ]
