# Generated by Django 4.0.5 on 2022-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0040_alter_product_image_alter_product_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
