# Generated by Django 4.0.5 on 2022-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0041_orderdetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
