# Generated by Django 4.0.5 on 2022-08-03 20:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0044_remove_user_location_alter_user_country_delete_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
