# Generated by Django 4.0.5 on 2022-08-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0048_city_alter_user_location_delete_grad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
