# Generated by Django 4.0.5 on 2022-08-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0049_remove_user_location_delete_city_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
