# Generated by Django 4.0.5 on 2022-08-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0052_drzava_grad_drzava'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='grad',
            new_name='location',
        ),
    ]
