# Generated by Django 4.0.5 on 2022-08-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0053_rename_grad_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(blank=True, max_length=100, null=True)),
                ('postanski', models.CharField(max_length=100, null=True)),
                ('grad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swoosh_app.grad')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swoosh_app.adresa'),
        ),
    ]
