# Generated by Django 4.0.5 on 2022-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0054_adresa_alter_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drzava',
            name='drzava',
        ),
        migrations.AddField(
            model_name='drzava',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drzava',
            name='iso_3166_1_numeric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drzava',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drzava',
            name='printable_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
