# Generated by Django 4.0.5 on 2022-08-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0055_remove_drzava_drzava_drzava_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drzava',
            new_name='Country',
        ),
    ]
