# Generated by Django 4.0.5 on 2022-08-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0056_rename_drzava_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grad',
            new_name='City',
        ),
    ]
