# Generated by Django 4.0.5 on 2022-08-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0057_rename_grad_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresa',
            old_name='adresa',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='adresa',
            old_name='grad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='adresa',
            old_name='postanski',
            new_name='postal_code',
        ),
    ]
