# Generated by Django 4.0.5 on 2022-08-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0058_rename_adresa_adresa_address_rename_grad_adresa_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresa',
            new_name='Address',
        ),
    ]
