# Generated by Django 4.0.5 on 2022-08-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0060_remove_user_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='city',
            old_name='grad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='drzava',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_3166_1_numeric',
        ),
        migrations.RemoveField(
            model_name='country',
            name='printable_name',
        ),
        migrations.AddField(
            model_name='city',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swoosh_app.postal'),
        ),
    ]
