# Generated by Django 4.0.5 on 2022-08-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0061_postal_rename_grad_city_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
    ]
