# Generated by Django 4.0.5 on 2022-08-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0063_alter_city_postal_code_delete_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='postal_code',
        ),
    ]
