# Generated by Django 4.0.5 on 2022-08-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0066_postal_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swoosh_app.address'),
        ),
    ]
