# Generated by Django 4.0.6 on 2022-08-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0067_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swoosh_app.country'),
        ),
    ]
