# Generated by Django 4.0.6 on 2022-08-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0068_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
