# Generated by Django 4.0.5 on 2022-08-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoosh_app', '0072_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postal',
            name='postal_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
